export const data = [
  {
    img:[
      "https://data.cei.net.cn/images/advertisement/1650421246187.jpg",
      "https://data.cei.net.cn/images/advertisement/1646206522403.jpg"
    ],
    courseTop:[
      {
        img:"https://data.cei.net.cn/images/product/1624341234427.jpg",
        title:"第一集：环境综合服务市场占不住？业务实践大力拓展市场渠道！"
      },
      {
        img:"https://data.cei.net.cn/images/product/1624341234427.jpg",
        title:"第二集：你真的会做管家业务？业务以技术为主，技术以人才为主！"
      },
      {
        img:"https://data.cei.net.cn/images/product/1624341234427.jpg",
        title:"第三集：环保管家如何对待客户？专家给你5大利器！"
      },
    ],
    courseBottom:[
      {
        img:"https://data.cei.net.cn/images/product/1678783456408.jpg",
        title:"《生态环境综合服务（生态环保管家）及延伸》在线培训班"
      },
      {
        img:"https://data.cei.net.cn/images/product/1678783456408.jpg",
        title:"《生态环境综合服务（生态环保管家）及延伸》在线培训班"
      },
    ],
    message:[
      "生态环境部固体废物与化学品司有关负责人就《关于进一步加强危险废物规范化环境管理有关工作的通知》答记者问",
      "生态环境部固体废物与化学品司有关负责人就《关于进一步加强危险废物规范化环境管理有关工作的通知》答记者问",
      "生态环境部固体废物与化学品司有关负责人就《关于进一步加强危险废物规范化环境管理有关工作的通知》答记者问"
    ],
    issue:{
      quesiton:[
        "电厂冷却用的温排水是否属于清净下水?"
      ],
      answer:[
        "在排放标准中，一般不使用“清净下水”这一术语。但在日常环境管理中，一般认为清净下水包括温排水、锅炉循环水等。考虑到这类清净下水通常为循环水，运行中常需加入阻垢剂、杀菌剂、杀藻剂等，可能导致循环水化学需氧量、总磷超标，因此，多数排放标准将此类废水纳入管控范围，要求处理达标后方可排放。"
      ]
    },
    imgBanner:[
      "https://data.cei.net.cn/images/advertisement/1646271226382.jpg",
      "https://data.cei.net.cn/images/advertisement/1646271682744.jpg"
    ]
  },
  {
    img:[
      "https://data.cei.net.cn/images/advertisement/1650421246187.jpg",
      "https://data.cei.net.cn/images/advertisement/1646206522403.jpg"
    ],
    courseTop:[
      {
        img:"https://data.cei.net.cn/images/product/1624341234427.jpg",
        title:"第一集：环境综合服务市场占不住？业务实践大力拓展市场渠道！"
      },
      {
        img:"https://data.cei.net.cn/images/product/1624341234427.jpg",
        title:"第二集：你真的会做管家业务？业务以技术为主，技术以人才为主！"
      },
      {
        img:"https://data.cei.net.cn/images/product/1624341234427.jpg",
        title:"第三集：环保管家如何对待客户？专家给你5大利器！"
      },
    ],
    courseBottom:[
      {
        img:"https://data.cei.net.cn/images/product/1678783456408.jpg",
        title:"《生态环境综合服务（生态环保管家）及延伸》在线培训班"
      },
      {
        img:"https://data.cei.net.cn/images/product/1678783456408.jpg",
        title:"《生态环境综合服务（生态环保管家）及延伸》在线培训班"
      },
    ],
    message:[
      "生态环境部固体废物与化学品司有关负责人就《关于进一步加强危险废物规范化环境管理有关工作的通知》答记者问",
      "生态环境部固体废物与化学品司有关负责人就《关于进一步加强危险废物规范化环境管理有关工作的通知》答记者问",
      "生态环境部固体废物与化学品司有关负责人就《关于进一步加强危险废物规范化环境管理有关工作的通知》答记者问"
    ],
    issue:{
      quesiton:[
        "电厂冷却用的温排水是否属于清净下水?"
      ],
      answer:[
        "在排放标准中，一般不使用“清净下水”这一术语。但在日常环境管理中，一般认为清净下水包括温排水、锅炉循环水等。考虑到这类清净下水通常为循环水，运行中常需加入阻垢剂、杀菌剂、杀藻剂等，可能导致循环水化学需氧量、总磷超标，因此，多数排放标准将此类废水纳入管控范围，要求处理达标后方可排放。"
      ]
    },
    imgBanner:[
      "https://data.cei.net.cn/images/advertisement/1646271226382.jpg",
      "https://data.cei.net.cn/images/advertisement/1646271682744.jpg"
    ]
  },
  {
    img:[
      "https://data.cei.net.cn/images/advertisement/1650421246187.jpg",
      "https://data.cei.net.cn/images/advertisement/1646206522403.jpg"
    ],
    courseTop:[
      {
        img:"https://data.cei.net.cn/images/product/1624341234427.jpg",
        title:"第一集：环境综合服务市场占不住？业务实践大力拓展市场渠道！"
      },
      {
        img:"https://data.cei.net.cn/images/product/1624341234427.jpg",
        title:"第二集：你真的会做管家业务？业务以技术为主，技术以人才为主！"
      },
      {
        img:"https://data.cei.net.cn/images/product/1624341234427.jpg",
        title:"第三集：环保管家如何对待客户？专家给你5大利器！"
      },
    ],
    courseBottom:[
      {
        img:"https://data.cei.net.cn/images/product/1678783456408.jpg",
        title:"《生态环境综合服务（生态环保管家）及延伸》在线培训班"
      },
      {
        img:"https://data.cei.net.cn/images/product/1678783456408.jpg",
        title:"《生态环境综合服务（生态环保管家）及延伸》在线培训班"
      },
    ],
    message:[
      "生态环境部固体废物与化学品司有关负责人就《关于进一步加强危险废物规范化环境管理有关工作的通知》答记者问",
      "生态环境部固体废物与化学品司有关负责人就《关于进一步加强危险废物规范化环境管理有关工作的通知》答记者问",
      "生态环境部固体废物与化学品司有关负责人就《关于进一步加强危险废物规范化环境管理有关工作的通知》答记者问"
    ],
    issue:{
      quesiton:[
        "电厂冷却用的温排水是否属于清净下水?"
      ],
      answer:[
        "在排放标准中，一般不使用“清净下水”这一术语。但在日常环境管理中，一般认为清净下水包括温排水、锅炉循环水等。考虑到这类清净下水通常为循环水，运行中常需加入阻垢剂、杀菌剂、杀藻剂等，可能导致循环水化学需氧量、总磷超标，因此，多数排放标准将此类废水纳入管控范围，要求处理达标后方可排放。"
      ]
    },
    imgBanner:[
      "https://data.cei.net.cn/images/advertisement/1646271226382.jpg",
      "https://data.cei.net.cn/images/advertisement/1646271682744.jpg"
    ]
  },
  {
    img:[
      "https://data.cei.net.cn/images/advertisement/1650421246187.jpg",
      "https://data.cei.net.cn/images/advertisement/1646206522403.jpg"
    ],
    courseTop:[
      {
        img:"https://data.cei.net.cn/images/product/1624341234427.jpg",
        title:"第一集：环境综合服务市场占不住？业务实践大力拓展市场渠道！"
      },
      {
        img:"https://data.cei.net.cn/images/product/1624341234427.jpg",
        title:"第二集：你真的会做管家业务？业务以技术为主，技术以人才为主！"
      },
      {
        img:"https://data.cei.net.cn/images/product/1624341234427.jpg",
        title:"第三集：环保管家如何对待客户？专家给你5大利器！"
      },
    ],
    courseBottom:[
      {
        img:"https://data.cei.net.cn/images/product/1678783456408.jpg",
        title:"《生态环境综合服务（生态环保管家）及延伸》在线培训班"
      },
      {
        img:"https://data.cei.net.cn/images/product/1678783456408.jpg",
        title:"《生态环境综合服务（生态环保管家）及延伸》在线培训班"
      },
    ],
    message:[
      "生态环境部固体废物与化学品司有关负责人就《关于进一步加强危险废物规范化环境管理有关工作的通知》答记者问",
      "生态环境部固体废物与化学品司有关负责人就《关于进一步加强危险废物规范化环境管理有关工作的通知》答记者问",
      "生态环境部固体废物与化学品司有关负责人就《关于进一步加强危险废物规范化环境管理有关工作的通知》答记者问"
    ],
    issue:{
      quesiton:[
        "电厂冷却用的温排水是否属于清净下水?"
      ],
      answer:[
        "在排放标准中，一般不使用“清净下水”这一术语。但在日常环境管理中，一般认为清净下水包括温排水、锅炉循环水等。考虑到这类清净下水通常为循环水，运行中常需加入阻垢剂、杀菌剂、杀藻剂等，可能导致循环水化学需氧量、总磷超标，因此，多数排放标准将此类废水纳入管控范围，要求处理达标后方可排放。"
      ]
    },
    imgBanner:[
      "https://data.cei.net.cn/images/advertisement/1646271226382.jpg",
      "https://data.cei.net.cn/images/advertisement/1646271682744.jpg"
    ]
  },
]